apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-pod
  namespace: service-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: service-api
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 1000m
              memory: 256Mi
