apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-pod
  namespace: sales-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      containers:
        # zipkin container configuration
        - name: zipkin
          resources:
            limits:
              cpu: "500m" # Up to 1/2 full core
              memory: "256Mi" # Up to 1/2 GB
            requests:
              cpu: "250m" # Use 1/4 full core
              memory: "128Mi" # Use 1/2 GB
        - name: sales-api
          resources:
            limits:
              cpu: 4000m
              memory: 512Mi
            requests:
              cpu: 2000m
              memory: 256Mi
