apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/sales-pod/
patches:
  - path: ./kind-sales-patch.yaml
images:
  - name: openzipkin
    newName: openzipkin/zipkin
    newTag: "2.23"
  - name: sales-api-image
    newName: sales-api-amd64
    newTag: "1.0"
