apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: sales-system
spec:
  selector:
    matchLabels:
      app: zipkin
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        # zipkin container configuration
        - name: zipkin
          image: openzipkin/zipkin:2.24
          ports:
            - name: zipkin
              containerPort: 9411
          resources:
            requests:
              cpu: "250m" # I need access to 1/4 core on the node.
              memory: 500Mi
            limits:
              cpu: "250m" # Execute instructions 25ms/100ms on my 1/2 core.
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: zipkin
  ports:
    - name: zipkin
      port: 9411
      targetPort: zipkin
